CREATE TABLE IF NOT EXISTS prefix (
    a0 INTEGER NOT NULL,
    a1 INTEGER NOT NULL,
    rand INTEGER NOT NULL,
    acquired INTEGER NOT NULL DEFAULT 0,
    submitted INTEGER NOT NULL DEFAULT 0,
    s0 INTEGER NOT NULL DEFAULT 0,
    s1 INTEGER NOT NULL DEFAULT 0,
    s2 INTEGER NOT NULL DEFAULT 0,
    s3 INTEGER NOT NULL DEFAULT 0,
    s4 INTEGER NOT NULL DEFAULT 0,
    s5 INTEGER NOT NULL DEFAULT 0,
    s6 INTEGER NOT NULL DEFAULT 0,
    s7 INTEGER NOT NULL DEFAULT 0,
    s8 INTEGER NOT NULL DEFAULT 0,
    magics INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY(a0, a1)
);

CREATE INDEX IF NOT EXISTS idx_acquired_rand ON prefix(acquired, rand);
